stages:
  - deploy

variables:
  SRC_DIR: "."
  DEST_DIR: "UAO-Theme"

deploy_to_hubspot:
  stage: deploy
  image: ubuntu:latest
  
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  
  before_script:
    - apt-get update -qy
    - apt-get install -y curl git nodejs npm
    
    - npm install -g @hubspot/cli
  
  script:
    - hs auth personalaccesskey --account=$HUBSPOT_ACCOUNT_ID --key=$HUBSPOT_PERSONAL_ACCESS_KEY
